#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Test Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select a branch'
      include_feeds:
        type: boolean
        description: 'include feeds'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: lovehackintosh/openwrt
        ref: '${{ github.event.inputs.branch }}'
        path: 'openwrt'

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt update
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt full-upgrade -y
        sudo -E apt install -y build-essential flex gawk gettext git libncurses5-dev libncurses6 libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo -E apt autoremove --purge
        sudo -E apt clean

    - name: Checkout packages feed
      if: inputs.include_feeds == true
      uses: actions/checkout@main
      with:
        repository: openwrt/packages
        path: openwrt/feeds/packages

    - name: Checkout luci feed
      if: inputs.include_feeds == true
      uses: actions/checkout@main
      with:
        repository: openwrt/luci
        path: openwrt/feeds/luci

    - name: Checkout routing feed
      if: inputs.include_feeds == true
      uses: actions/checkout@main
      with:
        repository: openwrt/routing
        path: openwrt/feeds/routing

    - name: Checkout telephony feed
      if: inputs.include_feeds == true
      uses: actions/checkout@main
      with:
        repository: openwrt/telephony
        path: openwrt/feeds/telephony

    - name: Checkout helloworld feed
      if: inputs.include_feeds == true
      uses: actions/checkout@main
      with:
        repository: fw876/helloworld
        path: openwrt/feeds/helloworld

    - name: Update & Install feeds
      if: inputs.include_feeds == true
      working-directory: openwrt
      run: |
        echo 'src-git helloworld https://github.com/fw876/helloworld' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: SSH
      uses: appleboy/ssh-action@master
      with:
        host: test
        username: clover
        password: 000


    - name: Download package
      working-directory: openwrt
      run: |
        wget https://github.com/lovehackintosh/Actions-OpenWrt/raw/openwrt/.config -O .config
        make defconfig
        ./scripts/diffconfig.sh
        gcc --version
        make download -j16

    - name: Compile the firmware
      working-directory: openwrt
      run: |
        make tools/install -j$(nproc)
        make toolchain/install -j$(nproc)
        make target/compile -j$(nproc)
        make -j$(nproc)

    - name: Check space usage
      run: df -hT
