#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Test Build OpenWrt

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: openwrt/openwrt
        path: 'openwrt'

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt update
        sudo -E apt full-upgrade -y
        sudo -E apt install -y build-essential flex gawk gcc-12 gettext git libncurses5-dev libncurses6 libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo -E apt autoremove --purge
        sudo -E apt clean

    - name: Make defconfig
      working-directory: openwrt
      run: |
        echo CONFIG_TARGET_ipq807x=y > .config
        make defconfig
        ./scripts/diffconfig.sh

    - name: Build tools
      working-directory: openwrt
      run: |
        make tools/install -j$(nproc)

    - name: Test build tools/squashfs4
      working-directory: openwrt
      run: |
        make tools/squashfs4/clean
        time make tools/squashfs4/compile -j$(nproc)
        make tools/squashfs4/clean
        time make tools/squashfs4/compile -j$(nproc)
        make tools/squashfs4/clean
        time make tools/squashfs4/compile -j$(nproc)


        make tools/squashfs4/clean
        sed -i '/HOST_BUILD_PARALLEL:=1/d' tools/squashfs4/Makefile
        make defconfig
        time make tools/squashfs4/compile -j$(nproc)
        make tools/squashfs4/clean
        time make tools/squashfs4/compile -j$(nproc)
        make tools/squashfs4/clean
        time make tools/squashfs4/compile -j$(nproc)
